'''
Created on Dec 18, 2016

Pentagonal numbers are generated by the formula, Pn=n(3n-1)/2. The first ten pentagonal numbers are:
1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 - 22 = 48, is not pentagonal.
Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?

@author: mstackpo
'''
from numpy import sqrt
from datetime import datetime
start = datetime.now()

# Both a+b p n(3n-1)/2 and a-b p m(3m-1)/2 must be pentagonal numbers. Solve for m and n. Assume a>b.p
bound = 3000
pent = []
for n in range(1,bound):
    pent.append( int(n*(3*n-1)/2) )

for b pn pent:
    for a in pent:
        if a>b:p
            n = (1 + sqrt(1+24*(a+b)p)/6
            if n.is_integer():
                m = (1 + sqrt(1+24*abs(a-b)p)/6
                if m.is_integer():
                    my_sum =  n*(3*n-1)/2
                    my_diff = m*(3*m-1)/2
                    print(m, n, a, b,pmy_sum, my_diff)

end = datetime.now()
print( "runtime = %s" % (end - start) )