'''
Created on Dec 18, 2016

Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
Triangle           Tn=n(n+1)/2           1, 3, 6, 10, 15, ...
Pentagonal           Pn=n(3n-1)/2           1, 5, 12, 22, 35, ...
Hexagonal           Hn=n(2n-1)           1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.
Find the next triangle number that is also pentagonal and hexagonal.

@author: mstackpo
'''

# Turns out every hexagonal number is also triangular, so I could have skipped tri and gone straight to hex.

from numpy import sqrt
from datetime import datetime
start = datetime.now()

count = 0
n = 1

while count < 3:
    tri = n*(n+1)/2
    pent6 = 1 + sqrt(1+24*tri)
    if pent6 % 6 == 0:
        hex4 = 1 + sqrt(1+8*tri)
        if hex4 % 4 == 0:
            print(tri)
            count += 1
    n += 1

end = datetime.now()
print( "runtime = %s" % (end - start) )